fail_fast: true
minimum_pre_commit_version: 3.7.1
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Lint
        language_version: python3.10
        language: python
        entry: black src/
        args:
          - --safe
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Code style
        language_version: python3.10
        language: python
        entry: flake8 src/
  - repo: local
    hooks:
      - id: update-coverage-badge
        name: update-coverage-badge
        entry: bash
        args:
          - ./pre-commit.sh
        language: system
        pass_filenames: false
