# .github/workflows/lint.yml
name: Lint
on:
  pull_request:
      branches:
        - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [ 3.10.x ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setting up python...
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Installing dependencies...
        run: pip install -U pip && pip install -r requirements-dev.txt

      - name: Running lint
        run: tox -e lint -q
