# .github/workflows/release.yml

name: Release
on:
  push:
    tags:
        - "*.*.*"

jobs:
  Release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [ 3.10.x ]
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setting up python...
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.x"

      - name: Installing project dependencies...
        run: pip install -U pip && pip install -r requirements-dev.txt

      - name: Installing pip packaging dependencies...
        run: | 
          pip install wheel
          pip install --upgrade build

      - name: Generating package dist
        run: python3 setup.py sdist bdist_wheel

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: >-
            ./dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes ""

      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/*.whl
          --repo '${{ github.repository }}'
